# Generated by Django 2.2.5 on 2019-12-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Obrigatório. Insira aqui seu nome.', max_length=100, verbose_name='Nome'),
        ),
    ]
