# Generated by Django 2.2.5 on 2019-12-26 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(help_text='Obrigatório. Nome do produto, de maior destaque na notícia.', max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('description', models.TextField(blank=True, help_text='Obrigatório. Uma descrição breve do produto. Max. 85 caracteres.', max_length=85, verbose_name='Descrição')),
                ('description_big', models.TextField(blank=True, help_text='Opcional. Uma descrição longa do produto. Max. 800 caracteres.', max_length=800, null=True, verbose_name='Descrição detalhada')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('image', models.ImageField(blank=True, help_text='Obrigatório. Envie aqui a foto da notícia.', null=True, upload_to='products', verbose_name='Imagem')),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Opcional, defina uma data futura, para que o Dashboard seja exibido somente a partir dela.', null=True, verbose_name='Data de exibição')),
                ('end_date', models.DateTimeField(blank=True, help_text='Opcional, defina uma data futura, para que o Dashboard deixe de ser exibido a partir dela.', null=True, verbose_name='Data de expiração')),
                ('created_by', models.CharField(default=0, editable=False, max_length=30, verbose_name='Criado por')),
                ('is_active', models.BooleanField(default=True, help_text='Determina se esse Dashboard deve ser tratado como ativo. Desmarque isso em vez de excluir dashboards.', verbose_name='Ativo')),
                ('category', models.ForeignKey(help_text='Determine a categoria do produto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Categoria', to='catalog.Category', verbose_name='Categoria')),
                ('property_product', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.PropertyProduct')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
    ]
