# Generated by Django 2.2.5 on 2019-12-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_by',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='property_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Obrigatório. Envie aqui fotos do produto.', null=True, upload_to='products', verbose_name='Imagem'),
        ),
        migrations.DeleteModel(
            name='PropertyProduct',
        ),
    ]
