# Generated by Django 2.2.5 on 2019-12-31 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimages',
            unique_together=set(),
        ),
    ]
