# Generated by Django 2.2.5 on 2019-09-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', related_name='Categoria', to='catalog.Category', verbose_name='Categoria'),
        ),
    ]
