# Generated by Django 2.2.5 on 2020-01-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191230_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_spotlight',
            field=models.BooleanField(default=False, help_text='Determina se essa Categoria deve ser inclusa nos Destaques da Página Inicial. Geralmente Categoria em destaque possuem promoções.', verbose_name='Destaque na págnina inicial'),
        ),
    ]
