# Generated by Django 2.2.5 on 2019-09-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190926_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', related_name='intervals', to='catalog.Category', verbose_name='Categoria'),
        ),
    ]
