# Generated by Django 2.2.5 on 2019-12-26 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191226_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Obrigatório. Uma descrição breve do Produto. Max. 85 caracteres.', max_length=85, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_big',
            field=models.TextField(blank=True, help_text='Opcional. Uma descrição longa do Produto. Max. 800 caracteres.', max_length=800, null=True, verbose_name='Descrição detalhada'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Opcional, defina uma data futura, para que o Produto deixe de ser exibido a partir dela.', null=True, verbose_name='Data de expiração'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Determina se esse Produto deve ser tratado como ativo. Desmarque isso em vez de excluir produtos.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Obrigatório. Nome do Produto, de maior destaque na página.', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Obrigatório. Determine um preço para o Produto.', max_digits=8, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Opcional, defina uma data futura, para que o Produto seja exibido somente a partir dela.', null=True, verbose_name='Data de exibição'),
        ),
    ]
