# Generated by Django 2.2.5 on 2020-01-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_home_spotlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Opcional. Envie aqui uma foto da categoria.', null=True, upload_to='categories', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='category',
            name='in_navbar',
            field=models.BooleanField(default=False, help_text='Determina se essa Categoria deve ser inclusa na barra superior do site.', verbose_name='Incluir na Barra Superior?'),
        ),
    ]
