# Generated by Django 2.2.5 on 2020-01-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200116_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Opcional. Envie uma foto para a categoria.', null=True, upload_to='categories', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(help_text='Obrigatório. Envie uma foto para o produto.', upload_to='products', verbose_name='Imagem'),
        ),
    ]
