# Generated by Django 2.2.5 on 2019-12-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191226_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(default='', editable=False, max_length=30, verbose_name='Criado por'),
        ),
    ]
