# Generated by Django 2.2.5 on 2020-01-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200116_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='home_spotlight',
            field=models.BooleanField(default=False, help_text='Determina se essa Categoria deve ser inclusa nos Destaques da Página Inicial. Geralmente Categoria em destaque possuem promoções.', verbose_name='Destaque na página inicial'),
        ),
    ]
