# Generated by Django 2.2.5 on 2020-01-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200116_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category_father',
            field=models.ForeignKey(help_text='Determine a categoria o essa subcategoria será associada.', on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Categoria'),
        ),
    ]
