# Generated by Django 2.2.5 on 2019-12-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20191205_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_key',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Chave do Carrinho'),
        ),
    ]
