# Generated by Django 2.2.5 on 2019-12-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191128_1126'),
        ('checkout', '0008_auto_20191211_1606'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart_key', 'product')},
        ),
    ]
