# Generated by Django 2.2.5 on 2019-12-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20191212_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('boletobancario', 'Boleto Bancário'), ('pagseguro', 'PagSeguro'), ('paypal', 'PayPal')], default='boletobancario', max_length=30, verbose_name='Modo de Pagamento'),
        ),
    ]
