# Generated by Django 2.2.5 on 2019-12-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20191212_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('boletobancario', 'Boleto Bancário'), ('pagseguro', 'PagSeguro'), ('paypal', 'PayPal')], default=None, max_length=30, null=True, verbose_name='Modo de Pagamento'),
        ),
    ]
