# Generated by Django 2.2.5 on 2019-12-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20191212_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[('1', 'Aguardando Pagamento'), ('2', 'Pagamento em Análise'), ('3', 'Pagamento Autorizado'), ('7', 'Cancelado')], default=1, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.Order', verbose_name='Pedido'),
        ),
    ]
